name: Liquibase Pipeline
 
on:
  push:
    branches:
      - main
 
jobs:
  liquibase:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
 
    - name: Run Liquibase
      run: |
        wget https://github.com/liquibase/liquibase/releases/download/v4.19.0/liquibase-4.19.0.tar.gz
        tar -xzf liquibase-4.19.0.tar.gz
        ./liquibase  --url=jdbc:mysql://192.168.67.128:3306/liquibase --username=sa  --password=P@ssw0rd update   
