name: Atlas_CI

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  Atlas_inspect:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Atlas inspect
        run: atlas schema inspect -u "mysql://root:P@ssw0rd@localhost/test" --format '{{ sql . }}' > schema.sql

      - name: Upload schema.sql as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: schema.sql
          path: schema.sql

  prepare_the_deploy:
    runs-on: self-hosted
    needs: Atlas_inspect
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download schema.sql
        uses: actions/download-artifact@v2
        with:
          name: schema.sql

      - name: Append content to schema.sql
        run: cat deploy1.sql >> schema.sql

      - name: Commit and push updated schema.sql
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add schema.sql
          git commit -m "Update schema.sql with latest changes" || echo "No changes to commit."
          git push

  make_the_deploy:
    runs-on: self-hosted
    needs: prepare_the_deploy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download updated schema.sql
        uses: actions/download-artifact@v2
        with:
          name: schema.sql

      - name: Start deploy
        run: atlas schema apply --auto-approve -u "mysql://root:P@ssw0rd@localhost/test" --to file://schema.sql --dev-url "mysql://root:P@ssw0rd@localhost/test2"
