# This is a workflow to run DB queries by Liquibase

name: Atlas_CI

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 20 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Job to check the status of the database
  Altas_inspect:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Runs a single command using the runner's shell
      - name: Run Altas inspect
        run:  atlas schema inspect -u "mysql://root:P@ssw0rd@localhost/test" --format '{{ sql . }}' > schema.sql

  # Job to validate database changes
  prepare_the_depoy:
    runs-on: self-hosted
    #needs: database_status

    steps:
    - name: Read content of file1.txt
      id: read_file1
      run: echo "::set-output name=content::$(cat schema.sql)"

    - name: Append content to file2.txt
      run: echo "${{ steps.read_file1.outputs.content }}" >> deploy1.sql

    - name: Commit changes
      run: |
        git add deploy1.sql
        git commit -m "Append content from schema.sql"
        git push
        
      
  
