name: Atlas_CI

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  Atlas_inspect:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Atlas inspect
        run: atlas schema inspect -u "mysql://root:P@ssw0rd@localhost/test" --format '{{ sql . }}' > schema.sql

      - name: Commit schema file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "mouda77"
          git add schema.sql
          git commit -m "commit schema file" || echo "No changes to commit"
          git fetch origin
          git merge origin/main
          git pull origin main --ff-only

      - name: Push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: git push https://mouda77:${GH_TOKEN}@github.com/mouda77/demo.git HEAD:main


  prepare_the_deploy:
    runs-on: self-hosted
    needs: Atlas_inspect
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read content of deploy1.sql
        id: read_file1
        run: echo "::set-output name=content::$(cat deploy1.sql)"

      - name: Append content to schema.sql
        run: echo "${{ steps.read_file1.outputs.content }}" >> schema.sql

      - name: Commit new changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "mouda77"
          git add schema.sql
          git commit -m "Append content from deploy1.sql" || echo "No changes to commit"
          git fetch origin
          git merge origin/main
          git pull origin main --ff-only

      - name: Push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: git push https://mouda77:${GH_TOKEN}@github.com/mouda77/demo.git HEAD:main

  make_the_deploy:
    runs-on: self-hosted
    needs: prepare_the_deploy
    steps:
      - name: Start deploy
        run: atlas schema apply --auto-approve -u "mysql://root:P@ssw0rd@localhost/test" --to file://schema.sql --dev-url "mysql://root:P@ssw0rd@localhost/test2"
