name: Atlas_CI

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  Atlas_inspect:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Atlas inspect
        run: atlas schema inspect -u "mysql://root:P@ssw0rd@localhost/test" --format '{{ sql . }}' > schema.sql

      - name: Commit schema file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add schema.sql
          git commit -m "Update schema.sql with Atlas inspect output" || echo "No changes to commit."
          git push

  prepare_the_deploy:
    runs-on: self-hosted
    needs: Atlas_inspect
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Append content to schema.sql and commit
        run: |
          cat deploy1.sql >> schema.sql
          git add schema.sql
          git diff --staged --quiet || git commit -m "Append content from deploy1.sql to schema.sql"

      - name: Fetch the latest history
        run: git fetch --prune

      - name: Rebase local changes on top of the fetched main branch
        run: git rebase origin/main

      - name: Push changes
        run: git push origin HEAD:main

  make_the_deploy:
    runs-on: self-hosted
    needs: prepare_the_deploy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start deploy
        run: atlas schema apply --auto-approve -u "mysql://root:P@ssw0rd@localhost/test" --to file://$(pwd)/schema.sql --dev-url "mysql://root:P@ssw0rd@localhost/test2"
