name: author

on:
  workflow_dispatch:
    inputs:
      author:
        description: 'Enter a value for author'
        required: true

jobs:
  author-input:
    runs-on: self-hosted

    steps:
    - name: Set Variable from User Input
      run: |
        CHANGESET_AUTHOR="${{ github.event.inputs.author }}"
        echo "CHANGESET_AUTHOR=$CHANGESET_AUTHOR" >> $GITHUB_ENV
        echo "CHANGESET_AUTHOR=${{ env.CHANGESET_AUTHOR }}"

  # Add a separate step to modify changeset.xml
  modify-changeset:
    runs-on: self-hosted
    needs: author-input
    steps:
      - name: Modify Changelog.xml
        run: |
          new_author_value="${{ env.CHANGESET_AUTHOR }}"
          sed -i "s/author='[^']*'/author='$new_author_value'/" Changelog.xml

  database_status:
    runs-on: self-hosted
    needs: modify-changeset
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run liquibase status
        run: liquibase --classpath=/var/lib/mysql/mysql-connector-j-8.0.31.jar status --url=jdbc:mysql://10.3.1.18:3306/liquibase --changeLogFile=Changelog.xml --username=newuser --password=${{ secrets.DB_PASSWORD }}

  validate:
    runs-on: self-hosted
    needs: database_status
    steps:
      - name: Run liquibase validate
        run: liquibase --classpath=/var/lib/mysql/mysql-connector-j-8.0.31.jar validate --url=jdbc:mysql://10.3.1.18:3306/liquibase --changeLogFile=Changelog.xml --username=newuser --password=${{ secrets.DB_PASSWORD }}

  update:
    runs-on: self-hosted
    needs: validate
    steps:
      - name: Run liquibase update
        run: liquibase --classpath=/var/lib/mysql/mysql-connector-j-8.0.31.jar update --url=jdbc:mysql://10.3.1.18:3306/liquibase --changeLogFile=Changelog.xml --username=newuser --password=${{ secrets.DB_PASSWORD }}
