name: authur

on:
  workflow_dispatch:
    inputs:
      authur:
        description: 'Enter a value for authur'
        required: true

jobs:
  user-input:
    runs-on: self-hosted

    steps:
    - name: Set Variable from User Input
      run: echo "authur=${{ github.event.inputs.authur }}" 

   
