name: User Input Example

on:
  workflow_dispatch:
    inputs:
      my_variable:
        description: 'Enter a value for MY_VARIABLE'
        required: true

jobs:
  user-input:
    runs-on: ubuntu-latest

    steps:
    - name: Set Variable from User Input
      run: echo "MY_VARIABLE=${{ github.event.inputs.my_variable }}" >> $GITHUB_ENV

    - name: Display Variable
      run: echo "Value of MY_VARIABLE: ${{ env.MY_VARIABLE }}"

    - name: Use Variable in Another File
      run: |
        echo "export MY_VARIABLE=${{ env.MY_VARIABLE }}" >> another_file.sh
        cat another_file.sh
