name: User Input Example

on:
  workflow_dispatch:
    inputs:
      my_variable:
        description: 'Enter a value for MY_VARIABLE'
        required: true

jobs:
  user-input:
    runs-on: self-hosted

    steps:
    - name: Set Variable from User Input
      run: echo "MY_VARIABLE=${{ github.event.inputs.my_variable }}" 

   

    - name: Use Variable
      run: |
        source my_variable_file.txt
        echo "Value of MY_VARIABLE: $MY_VARIABLE"
